name: Render and Build

on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 */12 * * *'

jobs:
  docker-public:
    name: Docker Public Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Cache Notebooks Cache
        id: cache-notebooks-cache
        uses: actions/cache@v3
        with:
          path: notebooks/cache
          key: notebooks-cache-${{ github.sha }}
          restore-keys: |
            notebooks-cache-${{ github.sha }}
            notebooks-cache-
            notebooks-
      - run: du -hs notebooks/cache

      - run: echo "RIOT_API_KEY=${{ secrets.RIOT_API_KEY }}" > .env
      - run: make chmod-data-cache

      - run: make setup-julia
      - run: make export pack-data
      - run: make build-public-image

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make docker-push-public

  render:
    name: Render
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Cache Notebooks Cache
        id: cache-notebooks-cache
        uses: actions/cache@v3
        with:
          path: notebooks/cache
          key: notebooks-cache-${{ github.sha }}
          restore-keys: |
            notebooks-cache-${{ github.sha }}
            notebooks-cache-
            notebooks-
      - run: du -hs notebooks/cache

      - run: echo "RIOT_API_KEY=${{ secrets.RIOT_API_KEY }}" > .env
      - run: make chmod-data-cache
      - run: touch notebooks/meta.html
      - run: chmod 777 notebooks/*.html

      - run: make setup-julia
      - run: make export
      - run: make export-notebooks

      - name: publish
        run: make setup-git public publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_NAME: Max Gonzih via GH Actions
          GIT_EMAIL: gonzih@gmail.com
